export default {
    en: {
        "nav.home": "Home",
        "nav.products": "Products",
        "nav.about": "About us",
        "nav.contact": "Contact",
        "ourservices.title": "Our services",
        "ourservices.btnseemore": "See more",
        "contact.title": "Contact",
        "contact.subtitle": "Get in touch for any question",
        "contact.subtitleform": "Your Details",
        "contact.contactinformation": "ENGLISH AAAAA",
        "contact.form.name": "Name",
        "contact.form.phone": "Phone",
        "contact.form.email": "Email",
        "contact.form.message": "Message",
        "contact.form.send": "Send",
        "section.check1": "ENGLISH de inversión a corto plazo",
        "section.check2": "ENGLISH la temperatura hasta 72 hs",
        "section.check3": "ENGLISH alcanza entre 70°C y 100°C",
        "section.check4": "ENGLISH no genera CO2",
        "section.check5": "ENGLISH probada en mas de 100 paises",
        "section.check6": "ENGLISH 80 ahorro energético",
        "section.check7": "ENGLISH Silencioso",
        "section.check8": "ENGLISH Resistente a lluvia viento y granizo",
        "section.check9": "ENGLISH 5 años de garantía",
        "section.check10": "ENGLISH 25 años de vida útil"
    },
    es: {
        "nav.home": "Inicio",
        "nav.products": "Productos",
        "nav.about": "Nosotros",
        "nav.contact": "Contacto",
        "ourservices.title": "Nuestro servicios",
        "ourservices.btnseemore": "Ver más",
        "contact.title": "Contacto",
        "contact.subtitle": "Póngase en contacto por cualquier consulta",
        "contact.contactinformation": "Datos de contacto",
        "contact.subtitleform": "Tus datos",
        "contact.form.name": "Nombre",
        "contact.form.phone": "Teléfono",
        "contact.form.email": "Correo electrónico",
        "contact.form.message": "Mensaje",
        "contact.form.send": "Enviar",
        "section.check1": "Retorno de inversión a corto plazo",
        "section.check2": "Conserva la temperatura hasta 72 hs",
        "section.check3": "El agua alcanza entre 70°C y 100°C",
        "section.check4": "100% Ecológico no genera CO2",
        "section.check5": "Tecnología probada en mas de 100 paises",
        "section.check6": "Hasta 80% de ahorro",
        "section.check7": "Silencioso",
        "section.check8": "Resistente a lluvia viento y granizo",
        "section.check9": "5 años de garantía",
        "section.check10": "25 años de vida útil"
    }
};